# Maze/tile and screen parameters
TILEWIDTH = 16
TILEHEIGHT = 16
NROWS = 36
NCOLS = 28
SCREENWIDTH = NCOLS*TILEWIDTH
SCREENHEIGHT = NROWS*TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)

# Colors
BLACK = (0,0,0)
YELLOW = (255,255,0)
WHITE = (255,255,255)
RED = (255,0,0)

# Directions
STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2
PORTAL = 3

# Entity types
PACMAN = 0
PELLET = 1
GHOST = 2

# Text
SCORETXT = 0
LEVELTXT = 1
READYTXT = 2
PAUSETXT = 3
GAMEOVERTXT = 4
METRICSTXT = 5
